services:
  postgres:
    image: postgres:17
    container_name: postgres-jdbc

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sistema

    ports:
      - "5433:5433"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: